package singbox

import (
	"encoding/base64"
	"encoding/json"
	"net/url"
	"strconv"
)

// GenerateShareLinks returns sb.sh-compatible single-node share links for each
// server inbound generated by BuildServerConfig.
func GenerateShareLinks(opts ServerConfigOptions) (map[string]string, error) {
	if err := validateServerConfigOptions(opts); err != nil {
		return nil, err
	}

	wsPath := opts.WebSocketPath
	if wsPath == "" {
		wsPath = "/vmessws"
	}
	if wsPath[0] != '/' {
		wsPath = "/" + wsPath
	}
	sni := opts.RealitySNI
	if sni == "" {
		sni = "apple.com"
	}
	name := opts.Hostname
	if name == "" {
		name = "sing-box"
	}

	links := map[string]string{}

	vlessParams := url.Values{}
	vlessParams.Set("encryption", "none")
	vlessParams.Set("flow", "xtls-rprx-vision")
	vlessParams.Set("security", "reality")
	vlessParams.Set("sni", sni)
	vlessParams.Set("fp", "chrome")
	vlessParams.Set("pbk", opts.RealityPublicKey)
	vlessParams.Set("sid", opts.RealityShortID)
	vlessParams.Set("type", "tcp")
	vlessParams.Set("headerType", "none")
	links["vless"] = "vless://" + opts.UUID + "@" + opts.ExternalHost + ":" + strconv.Itoa(opts.VlessRealityPort) + "?" + vlessParams.Encode() + "#vl-reality-" + url.QueryEscape(name)

	vmessPayload := map[string]string{
		"v":    "2",
		"ps":   "vm-ws-" + name,
		"add":  opts.ExternalHost,
		"port": strconv.Itoa(opts.VmessWebSocketPort),
		"id":   opts.UUID,
		"aid":  "0",
		"net":  "ws",
		"type": "none",
		"host": opts.ExternalHost,
		"path": wsPath,
		"tls":  "",
	}
	vmessJSON, err := json.Marshal(vmessPayload)
	if err != nil {
		return nil, err
	}
	links["vmess"] = "vmess://" + base64.RawStdEncoding.EncodeToString(vmessJSON)

	hy2Params := url.Values{}
	hy2Params.Set("security", "tls")
	hy2Params.Set("alpn", "h3")
	hy2Params.Set("sni", sni)
	hy2Params.Set("insecure", "0")
	hy2Params.Set("allowInsecure", "0")
	links["hysteria2"] = "hysteria2://" + url.QueryEscape(opts.Password) + "@" + opts.ExternalHost + ":" + strconv.Itoa(opts.Hysteria2Port) + "?" + hy2Params.Encode() + "#hy2-" + url.QueryEscape(name)

	tuicParams := url.Values{}
	tuicParams.Set("congestion_control", "bbr")
	tuicParams.Set("udp_relay_mode", "native")
	tuicParams.Set("alpn", "h3")
	tuicParams.Set("sni", sni)
	tuicParams.Set("insecure", "0")
	tuicParams.Set("allowInsecure", "0")
	links["tuic"] = "tuic://" + opts.UUID + ":" + url.QueryEscape(opts.Password) + "@" + opts.ExternalHost + ":" + strconv.Itoa(opts.TUICPort) + "?" + tuicParams.Encode() + "#tu5-" + url.QueryEscape(name)

	anytlsParams := url.Values{}
	anytlsParams.Set("sni", sni)
	anytlsParams.Set("insecure", "0")
	links["anytls"] = "anytls://" + url.QueryEscape(opts.Password) + "@" + opts.ExternalHost + ":" + strconv.Itoa(opts.AnyTLSPort) + "?" + anytlsParams.Encode() + "#anytls-" + url.QueryEscape(name)

	return links, nil
}
